In [7]:
class Employee:
    count = 0
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.count += 1
    def averageSalary(self):
        avg = self.salary / Employee.count
        return avg

class FulltimeEmployee(Employee):
    def _init_(self, name, family, salary, department):
        Employee._init_(self, name, family, salary, department)

e1 = Employee("donny", "jessica", 67000, "Sales")
e2 = Employee("Maxwell", "Jim", 98000, "IT")
e3 = FulltimeEmployee("Samuel", "Smith", 42000, "HR")

print(e1.averageSalary())
print(e2.averageSalary())
print(e3.averageSalary())

22333.333333333332
32666.666666666668
14000.0


In [6]:
import numpy as np

# random vector of size 20 with float in the range 1-20
vector = np.random.uniform(1,20,20)
print("The original vector:" ,vector)

# reshape vector to 4 by 5
vector_reshaped = vector.reshape(4,5)
print("The reshaped vector before replace: ", vector_reshaped)

# replace max in each row by 0
vector_reshaped[np.arange(4),vector_reshaped.argmax(axis=1)] = 0
print("The reshaped vector after replace: " ,vector_reshaped)

The original vector: [17.51643005  9.85223809  5.48569236  8.36035396  4.19614987  4.45548152
  2.11292589  8.95254876 16.91829335  6.87651716  3.5759704   5.52342378
  2.72718334  5.95175311 16.46571496 15.24252456  6.60498224  7.76130834
 10.13098451 14.73256875]
The reshaped vector before replace:  [[17.51643005  9.85223809  5.48569236  8.36035396  4.19614987]
 [ 4.45548152  2.11292589  8.95254876 16.91829335  6.87651716]
 [ 3.5759704   5.52342378  2.72718334  5.95175311 16.46571496]
 [15.24252456  6.60498224  7.76130834 10.13098451 14.73256875]]
The reshaped vector after replace:  [[ 0.          9.85223809  5.48569236  8.36035396  4.19614987]
 [ 4.45548152  2.11292589  8.95254876  0.          6.87651716]
 [ 3.5759704   5.52342378  2.72718334  5.95175311  0.        ]
 [ 0.          6.60498224  7.76130834 10.13098451 14.73256875]]
